logs:
  - name: root
    level: debug
    formatter: "%d%T%m%n"
    appender:
      - type: StdoutLogAppender
        formatter: "%d{%Y-%m-%d %H:%M:%S}%Ttid: %t%Ttname: \
      %N%Tfid: %F%T[%p]%T[%c]%T%f:%l%T%m%n"
  - name: system
    level: debug
    formatter: "%d{%Y-%m-%d %H:%M:%S}%Ttid: %t%Ttname: \
      %N%Tfid: %F%T[%p]%T[%c]%T%f:%l%T%m%n"
    appender:
      # - type: FileLogAppender
      #   file: log.txt
      - type: StdoutLogAppender